services:
  db:
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'rockets'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: